### ISSUE TITLE
auto complete 

### ISSUE THREAD

**Issue by faris114** [FACN7/nem-week6-book-sharing#45]
since you havent pick good names that explain it would be nice to have comments your code on autocomplete may be good regarding functionality and efficient but it is definitely very hard to read when you work with teams you have to explain the code and the code flow is it would be nice to have some comments  explaining the code . 
I want to point out how important is to write readable code it is as important as writing the code itself it is like producing a machine that does something without producing a manual on how to use it...
![](https://media.giphy.com/media/uVtAU2EKHrsgifowFb/giphy.gif)

**Comment by mcorcias** [comment]
we gonna remove this feature
